---
#- name: Install the nginx rpm from a remote repo
#  apt:
#    name: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
#    state: present

- name: Install Nginx Service
  apt: name=nginx state=latest update_cache=true

- name: Update Nginx Configuration
  template: src=../templates/nginx.conf dest=/etc/nginx/conf.d/default.conf


# In case SELinux is enforced and Nginx gives error "Permission Denied to the client", uncomment below two sections
#- name: Allow SELinux on port 8081 to nginx process
#  shell: cat /var/log/audit/audit.log | grep nginx | grep denied | audit2allow -M mynginx
#  register: se_result
#- debug: msg="{{ se_result.stdout }}"
    
#- name: Execute SELinux module
#  shell: semodule -i mynginx.pp
#  register: audit_result
#  failed_when: "audit_result.rc != 0"
#  changed_when: false

- lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: 'ssl_prefer_server_ciphers on;'
    line: '#ssl_prefer_server_ciphers on;'

- name: Restart the Nginx service
  service: name=nginx state=restarted enabled=true

