---
- include_vars: ../../vars/default.yml


- name: Install Artifactory repo
  shell: echo "deb https://jfrog.bintray.com/artifactory-pro-debs xenial main" | sudo tee -a /etc/apt/sources.list
#  shell: sudo apt-get update

- name: update 
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Java and  Artifactory
  apt: allow_unauthenticated=yes pkg={{ item }} state=present
#  action:  apt pkg={{item}} state=installed
  with_items:
    - jfrog-artifactory-pro 
    - openjdk-8*
    - unzip
    - zip
    - wget
#  force: yes
  become: yes
#   become_user: root
#   allow_unauthenticated: yes
#  dpkg_options: 'force'
#   dpkg_options: 'force-confold,force-confdef'


- name: Download and Unzip MySQL JDBC jar file
  unarchive: 
    src: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.45.zip
    dest: /tmp/ 
    remote_src: yes

- name: Copy the MySQL JDBC jar file
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '/tmp/mysql-connector-java-5.1.45/mysql-connector-java-5.1.45-bin.jar', dest: '/opt/jfrog/artifactory/tomcat/lib/' }
    - { src: '/var/opt/jfrog/artifactory/misc/db/mysql.properties', dest: '/etc/opt/jfrog/artifactory/db.properties' }
 
- name: Update Mysql Configuration
  template: src=../templates/db.properties dest=/etc/opt/jfrog/artifactory/db.properties

- name: Restart the Artifactory service
  service: name=artifactory state=restarted enabled=true

